server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
        # proxy_pass http://localhost:8080;
    # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection 'upgrade';
        # proxy_set_header Host $host;
    # proxy_cache_bypass $http_upgrade;
    }

}







# BRAINS CONFIG
server {

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;
    server_name www.brains.e-conneq.com; # managed by Certbot


    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
        # proxy_pass http://localhost:8080;
    # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection 'upgrade';
        # proxy_set_header Host $host;
    # proxy_cache_bypass $http_upgrade;
    }



listen [::]:443 ssl ipv6only=on; # managed by Certbot
listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/brains.e-conneq.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/brains.e-conneq.com/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
if ($host = www.brains.e-conneq.com) {
    return 301 https://$host$request_uri;
} # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
server_name www.brains.e-conneq.com;
return 404; # managed by Certbot

}







# JOAN CONFIG
server {

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;
    server_name www.joan.e-conneq.com; # managed by Certbot


    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
        # proxy_pass http://localhost:8080;
    # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection 'upgrade';
        # proxy_set_header Host $host;
    # proxy_cache_bypass $http_upgrade;
    }

listen [::]:443 ssl; # managed by Certbot
listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/joan.e-conneq.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/joan.e-conneq.com/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
if ($host = www.joan.e-conneq.com) {
    return 301 https://$host$request_uri;
} # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
server_name www.joan.e-conneq.com;
return 404; # managed by Certbot


}





# KINGS CONFIG
server {

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;
    server_name www.kings.e-conneq.com; # managed by Certbot


    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
        # proxy_pass http://localhost:8080;
    # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection 'upgrade';
        # proxy_set_header Host $host;
    # proxy_cache_bypass $http_upgrade;
    }



listen [::]:443 ssl; # managed by Certbot
listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/kings.e-conneq.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/kings.e-conneq.com/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
if ($host = www.kings.e-conneq.com) {
    return 301 https://$host$request_uri;
} # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
server_name www.kings.e-conneq.com;
return 404; # managed by Certbot


}




# VISHI CONFIG
server {

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;
    server_name www.vishi.e-conneq.com; # managed by Certbot


    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
        # proxy_pass http://localhost:8080;
    # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection 'upgrade';
        # proxy_set_header Host $host;
    # proxy_cache_bypass $http_upgrade;
    }



listen [::]:443 ssl; # managed by Certbot
listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/vishi.e-conneq.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/vishi.e-conneq.com/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
if ($host = www.vishi.e-conneq.com) {
    return 301 https://$host$request_uri;
} # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
server_name www.vishi.e-conneq.com;
return 404; # managed by Certbot
}






#CCAST CONFIG
server {

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name www.ccast.e-conneq.com; # managed by Certbot


    location / {
            try_files $uri $uri/ =404;
    }

listen [::]:443 ssl; # managed by Certbot
listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/ccast.e-conneq.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/ccast.e-conneq.com/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
   if ($host = www.ccast.e-conneq.com) {
       return 301 https://$host$request_uri;
   } # managed by Certbot


       listen 80 ;
       listen [::]:80 ;
   server_name www.ccast.e-conneq.com;
   return 404; # managed by Certbot
}






# SCHOOL CONFIG
server {
    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;
    server_name school.e-conneq.com; # managed by Certbot


    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
        # proxy_pass http://localhost:8080;
    # proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection 'upgrade';
        # proxy_set_header Host $host;
    # proxy_cache_bypass $http_upgrade;
    }



listen [::]:443 ssl; # managed by Certbot
listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/school.e-conneq.com-0002/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/school.e-conneq.com-0002/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
   if ($host = www.school.e-conneq.com) {
       return 301 https://$host$request_uri;
   } # managed by Certbot


       listen 80 ;
       listen [::]:80 ;
   server_name www.school.e-conneq.com;
   return 404; # managed by Certbot
}


