export const MonthList: { id: number, value: string }[] = [
    { id: 1, value: "January" },
    { id: 2, value: "February" },
    { id: 3, value: "March" },
    { id: 4, value: "April" },
    { id: 5, value: "May" },
    { id: 6, value: "June" },
    { id: 7, value: "July" },
    { id: 8, value: "August" },
    { id: 9, value: "September" },
    { id: 10, value: "October" },
    { id: 11, value: "November" },
    { id: 12, value: "December" }
]

export const TimeSlotsList: string[] = [
    "08H-10H", "10H-12H", "13H-15H", "15H-17H", "17H-19H", "19H-21H",
]

export const TableRowClassName = {
    all: "dark:even:bg-blue-300 even:bg-blue-200 hover:bg-slate-300",
    sm: "h-10",
    md: "h-12",
    lg: "h-14"
}

export const ConstAccountLists = [
    "REGISTRATION", "TUITION", "SCHOLARSHIP",
]

export const ConstSpecialtyList = [
    "MEDICAL LABORATORY SCIENCES", "MIDWIFERY", "NURSING", "MIDWIFERY", "MEDICAL LABORATORY TECHNOLOGY", "PHARMACY TECHONOLOGY", "MEDICAL IMAGING TECHNOLOGY",
    "TECHNICIEN DE LABORATOIRE", "SAGE FEMME", "TECHNICIEN EN PHARMACIE", "ULTRASONOGRAPHY", "PHYSIOTHERAPY", "MEDICAL IMAGING TECHNOLOGY", "REPRODUCTIVE HEALTH", "DELEGUE MEDICALE",
    "KINÉSITHÉRAPIE", "SOINS INFIRMIERS", "RADIOLOGIE ET IMAGERIE", "NUTRITION ET DIÉTÉTIQUE", "HEALTH CARE MANAGEMENT", "DENTAL THERAPY",
    
    "TELECOMMUNICATION", "SOFTWARE ENGINEERING", "COMPUTER HANDWEAR MAINTENANCE", "NETWORK AND SECURITY", "INFORMATION SYSTEM MANAGEMENT", "DATABASE MANAGEMENT", 
    "GENIE CIVIL", "GENIE LOGICEL", "RESEAUX ET SECURITE", "CIVIL ENGINEERING TECHNOLOGY", "COMPUTER GRAPHICS AND WEB DESIGN", "ELECTRICAL POWER SYSTEM", "MECHANICAL MANUFACTURING", 
    "METAL CONSTRUCTION",
    
    "E-COMMERCE / DIGITAL MARKETING", "CUSTOM AND TRANSIT", "TOPOGRAPHY", "HOTEL MANAGEMENT AND CATERING", "TOURISM AND TRAVEL AGENCY MANAGEMENT",
    "PROJECT MANAGEMENT", "HUMAN RESOURCE MANAGEMENT", "BANKING AND FINANCE", "ACCOUNTANCY", "LOGISTIC AND TRANSPORT", "MARKETING", "PORT SHIPPING MANAGEMENT", 
    "INTERNATIONAL TRADE", "CORPORATE COMMUNICATION", "INSURANCE", "BUSINESS MANAGEMENT",
    
    "AGROPASTORAL ENGINEERING", "AGRICULTURAL BUSINESS", "INDUSTRIE ALIMENTAIRE", "CONSEILLER AGROPASTORAL", "PRODUCTION VÉGÉTABLE", "AQUACULTURE", 
    "FOOD TECHNOLOGY", "AGRICULTURAL PRODUCTION TECHNOLOGY","ANIMAL PRODUCTION", "CROP PRODUCTION", "PRODUCTION ANIMALE", 

    "BEAUTY ESTHETICS", "FASHION CLOTHING AND TEXTILE", "BAKERY AND FOOD PROCESSING", "OTHERS/AUTRE"
]
export const ConstProgramList = [
    "HND", "BTS", "BSC", "LICENSE", "MASTERS", "DPQ", "OND", "DQP"
]